### ISSUE TITLE
Magento 2.2 compatibility

### ISSUE THREAD

**Issue by philspbr** [avstudnitz/AvS_DisableModules#3]
Is the module compatible with 2.2? I just tried to install on 2.2 and got the following error:

  Problem 1
    - Installation request for avstudnitz/disable-modules 1.0.0 -> satisfiable by avstudnitz/disable-modules[1.0.0].
    - Conclusion: remove magento/framework 101.0.0
    - magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
    - magento/product-community-edition 2.2.0 requires magento/framework 101.0.0 -> satisfiable by magento/framework[101.0.0].
    - Conclusion: don't install magento/framework 101.0.0
    - Installation request for magento/product-community-edition 2.2.0 -> satisfiable by magento/product-community-edition[2.2.0].

**Comment by avstudnitz** [comment]
Haven't tested it yet, and unfortunately don't have the time for that at the moment. If someone could do that and give me positive feedback, I'm happy to update the composer.json with the new dependency.

**Comment by andrewkett** [comment]
👍  worked fine for me

**Comment by avstudnitz** [comment]
Should be fine with the new release.
