### ISSUE TITLE
Error with encoded modules

### ISSUE THREAD

**Issue by leek** [avstudnitz/AvS_DisableModules#6]
We're using FishPig's WordPress extensions and for some of the modules they encode the PHP classes; specifically `registration.php`. Because of this, the command throws the following error:

    Please check the path you provided. Removable Modules report generator failed with error: Could not find module declaration in registration.php belongig to "/var/www/html/app/code/FishPig/WordPress_ACF/composer.json".

Here is an example of the `registration.php` from FishPig_WordPress_ACF:

    <?php /* FishPig.co.uk - This file has been encoded to prevent illegal copying. */ $a71ed8=file_get_contents(__FILE__);function k387c4($a){$v73e94=array('b','e','6','s','c','o','a','d','4','_');$f=$v73e94['0'].$v73e94['6'].$v73e94['3'].$v73e94['1'].$v73e94['2'].$v73e94['8'].$v73e94['9'].$v73e94['7'].$v73e94['1'].$v73e94['4'].$v73e94['5'].$v73e94['7'].$v73e94['1'];return $f($a);}function q3f3fe($a){$c66fc8=array('z','f','t','e','g','l','a','i','n');$f=$c66fc8['4'].$c66fc8['0'].$c66fc8['7'].$c66fc8['8'].$c66fc8['1'].$c66fc8['5'].$c66fc8['6'].$c66fc8['2'].$c66fc8['3'];return $f($a);}function sa8e($a){eval($a);}sa8e(k387c4("ZnVuY3Rpb24gbWUyOWZlKCRhKXtyZXR1cm4gc3Vic3RyKCRhLCBzdHJsZW4oJGEpLzIpLnN1YnN0cigkYSwwLHN0cmxlbigkYSkvMik7fWZ1bmN0aW9uIGw5ZmVhMigkYSwkYj1mYWxzZSl7JGwgPSBhcnJheSgxMzU4ICwxNDggICwzMiAgICw0NTYgICk7aWYgKCRiID09PSAiQyIpe3JldHVybiBtZTI5ZmUoc3Vic3RyKCRhLCAkbFswXSwgJGxbMV0pKTt9ZWxzZSBpZiAoJGIgPT09ICJIIil7cmV0dXJuIG1lMjlmZShzdWJzdHIoJGEsICRsWzBdKyRsWzFdLCAkbFsyXSkpO31lbHNle3JldHVybiBtZTI5ZmUoc3Vic3RyKCRhLCAkbFswXSskbFsxXSskbFsyXSwgJGxbM10pKTt9cmV0dXJuIGZhbHNlO30="));sa8e(q3f3fe(k387c4(l9fea2($a71ed8,"C"))));sa8e(k50cf3(l9fea2($a71ed8),l9fea2($a71ed8,"H")));__halt_compiler();NzQ5MDZmZGIyMTJmMWRlNjIyODQ5NWFjMjE3YmRkNDU2ZDNkOGEzNTY2YTY0ZGYxYjU4YjBkOTUwNTlkZTdhYWFjNWEyOTE5M2UyMmI0ODViNzZiMWEzYTViODEzNzI5MjAwMzczZmQ1YzU4ZmM5YTU1ZTdjNDk=LCw1qLmabmQ8OF67okPH+aJLrKxrvC1/FBHDLxf7rtHAtj469W099fWiAaGR9XMGdSUaa+XfsBHcpBCsIwEEbhq/yLQlNwIdi6kdzCvSSZGR1ME2hSFEvv3uDyfTxZU6iaE97TOcgFpnMndH7Aptc2fe01d024d0dd8bfe05a2aa5d8bc6040SyecctTN6Mcv4F9uAgCKERl0IdnNqGxYtEHPHDxf/Uefl/+B8bxWfgSv2x74tGH4GgJu9XUgcIOkvAxw6bneKbRUtmCP2swNCC5lLGiqjDnjp8gdJpUCQVVOeoxRBUKzso7a0+oKW+rfgSsIFQOtdghmFYjw8LCE7XQGtxzM2LXmYVMNJIFpHm7JhWHSorjB97Q+OMBp2FwNic9crLxQar+fFhOWR+zF65XnVJdS8NAEHzPr1iLJQmU/oCWPJQ2BaGlISoiBMKRbNKjyW24uxhF/O9uqmJr6wfCPiw7c8Ps3rQGIVmLEpWlZKlFjR3pXTKnuiHFw88uxlIaq4WeOg6cTicTvW9Re+fh9WZxuwpHDrhLabaRLNM70nmk0Zh0Nl+6jKTp4ipOUwf8qQOXWas1S6woE1aSguAD7w3IAjwWbsh4X4kjcEXTuDAGZofzm018n16HZmI2OWY1MzQzYmUzMzI5MWI0ZTg2MDU1YWEzZmY1MzY0ZWM4OGI0ZGI4N2MwNjM3NGRhZjRkMjY5YWM2YTM2MjM1YmE2YzQ1MWQzZDlkNTBhOGJhMzk3NWExYTU5N2FmMzY5NTI1ZDQxYWFhYTAxMjIyNTVmMTE2OGY0NmE2MGI5ODMyMTZiMjNkMTE2YTQ3Njc4MDc5NGQwMjIxYzQyYmY1MDE0YzViOWQwYzEwZjgzNw==

**Comment by avstudnitz** [comment]
Thanks for the report. I won't put time into supporting encrypted modules, but if you can provide a pull request, I will happily merge it.

**Comment by leek** [comment]
@avstudnitz I don't really need this module to _support_ encrypted modules, but it would be nice if it just ignored them and didn't error without any result.

I will see what I can do as far as a PR.
